// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhT3s6-Yn1YZWnqu7LvN6zOH74s0u52Hw',
    appId: '1:277512477372:web:b135fa705c0e2ed4458eb9',
    messagingSenderId: '277512477372',
    projectId: 'flutter-firebase-alura-9f164',
    authDomain: 'flutter-firebase-alura-9f164.firebaseapp.com',
    storageBucket: 'flutter-firebase-alura-9f164.appspot.com',
    measurementId: 'G-KZED447S7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw-WKSuc11dGdeaBiSxvmaDdedXOJKPxI',
    appId: '1:277512477372:android:971a0fedc30557c4458eb9',
    messagingSenderId: '277512477372',
    projectId: 'flutter-firebase-alura-9f164',
    storageBucket: 'flutter-firebase-alura-9f164.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9UB40bqRq7zI7rg8ykI8XLHFJHJQ7k0U',
    appId: '1:277512477372:ios:03a0d8323ac3c9c5458eb9',
    messagingSenderId: '277512477372',
    projectId: 'flutter-firebase-alura-9f164',
    storageBucket: 'flutter-firebase-alura-9f164.appspot.com',
    iosBundleId: 'com.example.explorandoFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9UB40bqRq7zI7rg8ykI8XLHFJHJQ7k0U',
    appId: '1:277512477372:ios:f60904129e4ba4a3458eb9',
    messagingSenderId: '277512477372',
    projectId: 'flutter-firebase-alura-9f164',
    storageBucket: 'flutter-firebase-alura-9f164.appspot.com',
    iosBundleId: 'com.example.explorandoFirebase.RunnerTests',
  );
}
